# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ac34c6fd17cc24a59cd2a1e8bcd81dd49749c6463149bec830f7c55354fcd7cd929020c3ea9d1450750ada08db8da251fc183aedcd955564f0e242d9c551eb7

test:
  secret_key_base: 945ed3c6fb668a7e1e3d617b0ae1a401fbf1e96072b472158905f30159aa281a8c7eac997134cc7b333fb0a63780abeb1d001b7db3c201362dc49c8acd92ceaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
